ServerPCICFGUncore Class Reference
Object to access uncore counters in a socket/processor with microarchitecture codename SandyBridge-EP (Jaketown) or Ivytown-EP or Ivytown-EX.
#include <cpucounters.h>
Public Member Functions
ServerPCICFGUncore (uint32 socket_, PCM *pcm)
Initialize access data structures.
void program ()
Program performance counters (disables programming power counters)
uint64 getImcReads ()
Get the number of integrated controller reads (in cache lines)
uint64 getImcWrites ()
Get the number of integrated controller writes (in cache lines)
uint64 getIncomingDataFlits (uint32 port)
Get the number of incoming data flits to the socket through a port.
uint64 getOutgoingDataNonDataFlits (uint32 port)
Get the number of outgoing data and non-data flits from the socket through a port.
void program_power_metrics (int mc_profile)
Program power counters (disables programming performance counters)
void programServerUncoreMemoryMetrics (int rankA=-1, int rankB=-1)
Program memory counters (disables programming performance counters)
uint64 getQPIClocks (uint32 port)
Get number of QPI LL clocks on a QPI port.
uint64 getQPIL0pTxCycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving half-lane mode.
uint64 getQPIL1Cycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving shutdown mode.
uint64 getDRAMClocks (uint32 channel)
Get number DRAM channel cycles.
uint64 getMCCounter (uint32 channel, uint32 counter)
Direct read of memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
uint64 getQPILLCounter (uint32 port, uint32 counter)
Direct read of QPI LL PMU counter (counter meaning depends on the programming: power/performance/etc)
void freezeCounters ()
Freezes event counting.
void unfreezeCounters ()
Unfreezes event counting.
uint64 computeQPISpeed (const uint32 ref_core, const int cpumodel)
Measures/computes the maximum theoretical QPI link bandwidth speed in GByte/seconds.
void enableJKTWorkaround (bool enable)
Enable correct counting of various LLC events (with memory access perf penalty)
size_t getNumQPIPorts () const
Returns the number of detected QPI ports.
uint64 getQPILinkSpeed (const uint32 linkNr) const
Returns the speed of the QPI link.
void reportQPISpeed () const
Print QPI Speeds.
uint32 getNumMC () const
Returns the number of detected integrated memory controllers.
size_t getNumMCChannels () const
Returns the total number of detected memory channels on all integrated memory controllers.
Detailed Description
Object to access uncore counters in a socket/processor with microarchitecture codename SandyBridge-EP (Jaketown) or Ivytown-EP or Ivytown-EX.
Constructor & Destructor Documentation
ServerPCICFGUncore::ServerPCICFGUncore (uint32 socket_, PCM * pcm)
Initialize access data structures.
Parameters
socket_ socket id
pcm pointer to PCM instance
References PCM::getCPUBrandString(), PCM::getCPUModel(), getNumMCChannels(), getNumQPIPorts(), and PCM::getNumSockets().
Member Function Documentation
uint64 ServerPCICFGUncore::getDRAMClocks (uint32 channel)
Get number DRAM channel cycles.
Parameters
channel channel number
uint64 ServerPCICFGUncore::getIncomingDataFlits (uint32 port)
Get the number of incoming data flits to the socket through a port.
Parameters
port QPI port id
uint64 ServerPCICFGUncore::getMCCounter (uint32 channel, uint32 counter)
Direct read of memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
channel channel number
counter counter number
uint64 ServerPCICFGUncore::getOutgoingDataNonDataFlits (uint32 port)
Get the number of outgoing data and non-data flits from the socket through a port.
Parameters
port QPI port id
References getQPILLCounter().
uint64 ServerPCICFGUncore::getQPIClocks (uint32 port)
Get number of QPI LL clocks on a QPI port.
Parameters
port QPI port number
Referenced by computeQPISpeed().
uint64 ServerPCICFGUncore::getQPIL0pTxCycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving half-lane mode.
Parameters
port QPI port number
uint64 ServerPCICFGUncore::getQPIL1Cycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving shutdown mode.
Parameters
port QPI port number
uint64 ServerPCICFGUncore::getQPILLCounter (uint32 port, uint32 counter)
Direct read of QPI LL PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
port port number
counter counter number
Referenced by getOutgoingDataNonDataFlits().
void ServerPCICFGUncore::program_power_metrics (int mc_profile)
Program power counters (disables programming performance counters)
Parameters
mc_profile memory controller measurement profile. See description of profiles in pcm-power.cpp
void ServerPCICFGUncore::programServerUncoreMemoryMetrics (int rankA = -1, int rankB = -1)
Program memory counters (disables programming performance counters)
Parameters
rankA count DIMM rank1 statistics (disables memory channel monitoring)
rankB count DIMM rank2 statistics (disables memory channel monitoring)
References PCM::getCPUBrandString(), PCM::getCPUModel(), and PCM::getInstance().
The documentation for this class was generated from the following files:
cpucounters.h
cpucounters.cpp